from faker import Faker
fake = Faker()
print(f"Name: {fake.name()}")
print(f"Address: {fake.address()}")
print(f"Text: {fake.text()}")
print(f"Email: {fake.email()}")
print(f"Slug: {fake.slug()}")
print(f"URL: {fake.url()}")
print(f"URI: {fake.uri()}")
print(f"Password: {fake.password()}")
print(f"First Name: {fake.first_name()}")
print(f"Last Name: {fake.last_name()}")
print(f"Username: {fake.user_name()}")
print(f"Phone Number: {fake.phone_number()}")